version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  deploy_prod:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb

workflows:
  deploy:
    jobs:
      - run_tests:
        filters:
          branches:
            only: master
      - hold_dev:
          type: approval
          requires:
            - run_tests
          filters:
            branches:
              only: master
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - hold_dev
          filters:
            branches:
              only: master
      - hold_prod:
          type: approval
          requires:
            - heroku/deploy-via-git
          filters:
            branches:
              only: master
      - deploy_prod: # Use the pre-configured job, deploy-via-git
          requires:
            - hold_prod
          filters:
            branches:
              only: master
