apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
      tier: backend
  template:
    metadata:
      labels:
        app: flask-app
        tier: backend
    spec:
      containers:
        - name: flask-app
          image: dumaru/flask_app:dev
          ports:
            - name: http
              containerPort: 80
