apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app-service
    track: dev
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
# status:
#   loadBalancer:
#     ingress:
#       - hostname: a1763d0f385014467970064ceb794b79-1060176734.us-east-2.elb.amazonaws.com
