apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  # labels to add to all generated resources
  labels:
    kustomize.generated.resources: generated_dev
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: generated_dev
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: false
configMapGenerator:
  - name: nginx-config
    files:
      - conf/nginx-default.conf
resources:
  - backend_deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
