apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: my-nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx0
status:
  loadBalancer:
    ingress:
      - hostname: a1763d0f385014467970064ceb794b79-1060176734.us-east-2.elb.amazonaws.com
