apiVersion: v1
kind: Service
metadata:
  name: backend-gateway-svc
spec:
  selector:
    app: flask-app
    tier: backend
    track: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
